### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by qianse** [tonyke-bot/ore-miner#1]
error[E0599]: no function or associated item named `default` found for struct `state::hash::Hash` in the current scope
  --> C:\Users\Administrator\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ore-program-1.2.0\src\state\treasury.rs:42:31
   |
42 |             difficulty: Hash::default(),
   |                               ^^^^^^^ function or associated item not found in `Hash`
   |
  ::: C:\Users\Administrator\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ore-program-1.2.0\src\state\hash.rs:11:1
   |
11 | pub struct Hash(pub [u8; HASH_BYTES]);
   | --------------- function or associated item `default` not found for this struct
   |
   = help: items from traits can only be used if the trait is implemented and in scope
   = note: the following trait defines an item `default`, perhaps you need to implement it:
           candidate #1: `Default`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `ore-program` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
PS L:\ore-miner-main>

How Can I do？
![Uploading 微信截图_20240413165943.png…]()

**Comment by catursawah** [comment]
maybe you typo, use ./build-cuda-worker.sh
but any problem when build :
ore.cu(155): warning #177-D: variable "str_len" was declared but never referenced
   int str_len;
       ^

Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"

ore.cu(184): warning #177-D: variable "device_count" was declared but never referenced
      int device_count, block_size;
          ^

ore.cu(239): warning #177-D: variable "h_to_d_time" was declared but never referenced
   float h_to_d_time = 0.0;
         ^

ore.cu(240): warning #177-D: variable "comp_time" was declared but never referenced
   float comp_time = 0.0;
         ^
ore.cu(241): warning #177-D: variable "d_to_h_time" was declared but never referenced
   float d_to_h_time = 0.0;
         ^
ore.cu(242): warning #177-D: variable "total_time" was declared but never referenced
   float total_time = 0.0;
         ^
ore.cu(243): warning #177-D: variable "max_str_size" was declared but never referenced
   size_t max_str_size = 11 * sizeof(char);
          ^
ore.cu(244): warning #177-D: variable "digest_str_size" was declared but never referenced
   size_t digest_str_size = digest_size_bytes * sizeof(unsigned char);
          ^
