### ISSUE TITLE
number of keys must be a multiple of 25

### ISSUE THREAD

**Issue by fuhua898** [tonyke-bot/ore-miner#3]
thread 'main' panicked at src\bundle_mine_gpu.rs:66:13:
number of keys must be a multiple of 25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Does this mean I have to have 25 different wallet key files under the directory for it to run successfully？or can I change this run count from somewhere

**Comment by rluisr** [comment]
Why do we need 25 wallets?
This is a rudimentary question, but I am not familiar with Solana or ORE, so could you please tell me?

**Comment by rluisr** [comment]
Thank you for answering this ridiculous question. I understand now! Thanks again!

**Comment by rluisr** [comment]
Sorry for the repetitiveness. Please let me know if you don't mind.
I have 25 wallets and have deposited 0.1 SOL in each wallet.

When I run the register command I see an error indicating an insufficient balance.
How much should I have in each wallet?

```
cargo run --release -- --rpc masked --priority-fee 500000 register --key-folder /root/id_json
    Finished `release` profile [optimized + debuginfo] target(s) in 0.43s
     Running `target/release/ore-miner --rpc 'masked' --priority-fee 500000 register --key-folder /root/id_json`
[2024-04-14T13:27:42Z INFO  ore_miner::register] registering 24 accounts
[2024-04-14T13:27:44Z ERROR ore_miner::register] fail to simulate transaction: Error processing Instruction 4: custom program error: 0x1
```

**Comment by rluisr** [comment]
I found the cause of this. A simple transfer failure resulted in the SOL not being deposited in the wallet.
