### ISSUE TITLE
range end index 32 out of range for slice of length 10

### ISSUE THREAD

**Issue by mainframer** [tonyke-bot/ore-miner#8]
~/ore-miner$ cargo run --release -- --rpc 'https://wild-empty-sunset.solana-mainnet.quiknode.pro/58b024b737bbbe155d39d43ae5e784ac63ed1982' --priority-fee 500000 bundle-mine-gpu --key-folder ~/.config/solana/keys --max-adaptive-tip 400000 
    Finished `release` profile [optimized + debuginfo] target(s) in 0.55s
     Running `target/release/ore-miner --rpc 'https://wild-empty-sunset.solana-mainnet.quiknode.pro/58b024b787bbbe155d39de4ae5e789ac63ed1982' --priority-fee 500000 bundle-mine-gpu --key-folder /root/.config/solana/keys --max-adaptive-tip 400000`
[2024-04-14T05:01:22Z INFO  ore_miner::bundle_mine_gpu] 25 keys loaded
[2024-04-14T05:01:22Z INFO  ore_miner::bundle_mine_gpu] splitted signers into batches
[2024-04-14T05:01:22Z INFO  ore_miner::bundle_mine_gpu] subscribed to jito tip stream
thread 'main' panicked at src/main.rs:181:33:
range end index 32 out of range for slice of length 10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by mainframer** [comment]
Yes. I've ran ./build-cuda-worker.sh  and here is the log. 
```
~/ore-miner$ ./build-cuda-worker.sh 
ore.cu(155): warning #177-D: variable "str_len" was declared but never referenced

Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"

ore.cu(184): warning #177-D: variable "device_count" was declared but never referenced

ore.cu(239): warning #177-D: variable "h_to_d_time" was declared but never referenced

ore.cu(240): warning #177-D: variable "comp_time" was declared but never referenced

ore.cu(241): warning #177-D: variable "d_to_h_time" was declared but never referenced

ore.cu(242): warning #177-D: variable "total_time" was declared but never referenced

ore.cu(243): warning #177-D: variable "max_str_size" was declared but never referenced

ore.cu(244): warning #177-D: variable "digest_str_size" was declared but never referenced
```

```
~/ore-miner$ echo "1600000040ffffffffffffffffffffffffffffffffffffffffffffffffffffffff16e1dc4ef3f0d8c5b48c704e849a1401b2ece9996dc908aef3a8e7c3b52bb39367a6c4f30a982921716c17a91d07a0f1e4fe1523866dd77194ca009a915c54ca2ceb" | xxd -r -p | cargo run --release --bin nonce-worker-gpu
error: no bin target named `nonce-worker-gpu`.
Available bin targets:
    ore-miner
    nonce-worker
```

**Comment by mainframer** [comment]
~/ore-miner$ echo "1600000040ffffffffffffffffffffffffffffffffffffffffffffffffffffffff16e1dc4ef3f0d8c5b48c704e849a1401b2ece9996dc908aef3a8e7c3b52bb39367a6c4f30a982921716c17a91d07a0f1e4fe1523866dd77194ca009a915c54ca2ceb" | xxd -r -p | ./target/release/nonce-worker-gpu
Problem getting properties for device, exiting...

**Comment by p4rmal4t** [comment]
> what cards are you using for mining?


Is there a way to use this fork without having access to the jito? I stopped at the same part above

**Comment by p4rmal4t** [comment]
> i don't have a version without jito right now but contribution is welcomed!

Thanks for sharing, I requested access to jito but I haven't received it yet, I also don't know how to configure it hahaha

**Comment by Kokiiez** [comment]
Same issues here, using integrated CPU card

**Comment by mainframer** [comment]
> what cards are you using for mining?

RTX 3060.
But I tried RTX 4090 and now it works like a charm. thank you.
